# Generated by Django 5.0.7 on 2024-07-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mother_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.mothercategory'),
        ),
    ]
